# Generated by Django 4.1.7 on 2023-03-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("session", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="friendlist",
            name="data_inicio",
            field=models.CharField(max_length=100),
        ),
    ]
