# Generated by Django 4.1.7 on 2023-03-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_alter_session_data_criacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='qtd_max',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
