# Generated by Django 4.1.7 on 2023-03-28 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("session", "0002_alter_friendlist_data_inicio"),
    ]

    operations = [
        migrations.CreateModel(
            name="Armamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.CharField(max_length=120)),
                ("categoria_1", models.CharField(max_length=50)),
                ("categoria_2", models.CharField(max_length=50)),
                ("categoria_3", models.CharField(max_length=70)),
                ("alcance", models.CharField(max_length=50)),
                ("dano_passivo", models.CharField(max_length=120)),
                ("dano_ativo", models.IntegerField()),
                ("tipo", models.CharField(max_length=30)),
                ("espaco", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="ArmamentoUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "fk_armamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="session.armamento",
                    ),
                ),
                (
                    "fk_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
