# Generated by Django 4.1.7 on 2023-03-26 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0003_session_qtd_max'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='data_criacao',
            field=models.CharField(max_length=100),
        ),
    ]
