# Generated by Django 4.1.7 on 2023-03-29 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("session", "0004_armamento_fk_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rituais",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alcance", models.CharField(max_length=50)),
                ("dano_passivo", models.CharField(max_length=120)),
                ("dano_ativo", models.IntegerField()),
                ("tipo", models.CharField(max_length=30)),
                ("ocultismo", models.IntegerField()),
                ("categoria", models.CharField(max_length=50)),
                (
                    "fk_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Acessorios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fk_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
