# Generated by Django 4.1.7 on 2023-03-26 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0004_alter_session_data_criacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='qtd_max',
            field=models.IntegerField(null=True),
        ),
    ]
