# Generated by Django 4.1.7 on 2023-03-29 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("session", "0005_rituais_acessorios"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="acessorios",
            name="fk_user",
        ),
    ]
