# Generated by Django 4.1.7 on 2023-03-29 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("session", "0006_remove_acessorios_fk_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="acessorios",
            name="descricao",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="acessorios",
            name="espaco",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="acessorios",
            name="fk_user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="acessorios",
            name="obs",
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
    ]
