# Generated by Django 4.1.7 on 2023-03-26 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0006_alter_session_qtd_max'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='qtd_max',
        ),
    ]
