# Generated by Django 4.1.7 on 2023-03-29 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("session", "0007_acessorios_descricao_acessorios_espaco_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rituais",
            name="descricao",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="rituais",
            name="obs",
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name="rituais",
            name="alcance",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="rituais",
            name="categoria",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="rituais",
            name="dano_ativo",
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="rituais",
            name="dano_passivo",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name="rituais",
            name="fk_user",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="rituais",
            name="ocultismo",
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="rituais",
            name="tipo",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
