# Generated by Django 4.1.7 on 2023-04-02 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0013_pericia_pericias'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pericias',
            old_name='fk_Pericia',
            new_name='fk_pericia',
        ),
    ]
