# Generated by Django 4.1.7 on 2023-04-02 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0014_rename_fk_pericia_pericias_fk_pericia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('valor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Resistencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_resistencias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session.resistencia')),
                ('fk_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session.session')),
            ],
        ),
    ]
