# Generated by Django 4.1.7 on 2023-04-02 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0015_resistencia_resistencias'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resistencias',
            old_name='fk_resistencias',
            new_name='fk_resistencia',
        ),
    ]
