# Generated by Django 3.2.18 on 2023-04-03 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0017_auto_20230403_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='armamentos',
            name='created_at',
        ),
    ]
