# Generated by Django 4.1.7 on 2023-04-04 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("session", "0018_remove_armamentos_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Acessorio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=120)),
                ("descricao", models.CharField(max_length=120)),
                ("espaco", models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name="acessorios",
            name="descricao",
        ),
        migrations.RemoveField(
            model_name="acessorios",
            name="espaco",
        ),
        migrations.RemoveField(
            model_name="acessorios",
            name="fk_user",
        ),
        migrations.RemoveField(
            model_name="acessorios",
            name="obs",
        ),
        migrations.AddField(
            model_name="acessorios",
            name="fk_session",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="session.session",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="acessorios",
            name="fk_acessorio",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="session.acessorio",
            ),
            preserve_default=False,
        ),
    ]
