# Generated by Django 4.1.7 on 2023-03-28 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Antescendente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(blank=True, max_length=100, null=True)),
                ("descricao", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Antescendentes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fk_Antescendente",
                    models.ManyToManyField(
                        blank=True, null=True, to="personagem.antescendente"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Armamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(blank=True, max_length=100, null=True)),
                ("categoria_1", models.IntegerField()),
                (
                    "categoria_2",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("dano", models.IntegerField()),
                ("critico", models.CharField(blank=True, max_length=100, null=True)),
                ("alcance", models.IntegerField()),
                ("tipo", models.CharField(blank=True, max_length=100, null=True)),
                ("peso", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Atributo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(blank=True, max_length=100, null=True)),
                ("valor", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Atributos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fk_Atributo",
                    models.ManyToManyField(
                        blank=True, null=True, to="personagem.atributo"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EsforcoBar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("atual", models.IntegerField()),
                ("maximo", models.IntegerField()),
                ("temporario", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.CharField(blank=True, max_length=100, null=True)),
                ("peso", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Iventario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("espaco_total", models.IntegerField()),
                (
                    "fk_armamento",
                    models.ManyToManyField(
                        blank=True, null=True, to="personagem.armamento"
                    ),
                ),
                (
                    "fk_item",
                    models.ManyToManyField(blank=True, null=True, to="personagem.item"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OcultismoBar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("atual", models.IntegerField()),
                ("maximo", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Pericia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(blank=True, max_length=100, null=True)),
                ("valor", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Pericias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fk_Pericia",
                    models.ManyToManyField(
                        blank=True, null=True, to="personagem.pericia"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Resistencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(blank=True, max_length=100, null=True)),
                ("valor", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="SanidadeBar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("atual", models.IntegerField()),
                ("maximo", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="VidaBar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("atual", models.IntegerField()),
                ("maximo", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Resistencias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fk_Resistencia",
                    models.ManyToManyField(
                        blank=True, null=True, to="personagem.resistencia"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Personagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(blank=True, max_length=100, null=True)),
                ("origem", models.CharField(blank=True, max_length=100, null=True)),
                ("idade", models.IntegerField()),
                (
                    "naturalidade",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("residencia", models.CharField(blank=True, max_length=100, null=True)),
                ("classe", models.CharField(blank=True, max_length=100, null=True)),
                ("NEX", models.IntegerField()),
                (
                    "fk_antescendentes",
                    models.OneToOneField(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="personagem.antescendentes",
                    ),
                ),
                (
                    "fk_atributos",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="personagem.atributos",
                    ),
                ),
                (
                    "fk_esforco",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="personagem.esforcobar",
                    ),
                ),
                (
                    "fk_iventario",
                    models.OneToOneField(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="personagem.iventario",
                    ),
                ),
                (
                    "fk_ocultismo",
                    models.OneToOneField(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="personagem.ocultismobar",
                    ),
                ),
                (
                    "fk_pericias",
                    models.OneToOneField(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="personagem.pericias",
                    ),
                ),
                (
                    "fk_resistencias",
                    models.OneToOneField(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="personagem.resistencias",
                    ),
                ),
                (
                    "fk_sanidade",
                    models.OneToOneField(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="personagem.sanidadebar",
                    ),
                ),
                (
                    "fk_vida",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="personagem.vidabar",
                    ),
                ),
            ],
        ),
    ]
