# Generated by Django 4.1.7 on 2023-03-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personagem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='antescendentes',
            name='fk_Antescendente',
        ),
        migrations.RemoveField(
            model_name='atributos',
            name='fk_Atributo',
        ),
        migrations.RemoveField(
            model_name='iventario',
            name='fk_armamento',
        ),
        migrations.RemoveField(
            model_name='iventario',
            name='fk_item',
        ),
        migrations.RemoveField(
            model_name='pericias',
            name='fk_Pericia',
        ),
        migrations.RemoveField(
            model_name='resistencias',
            name='fk_Resistencia',
        ),
        migrations.AddField(
            model_name='antescendentes',
            name='fk_Antescendente',
            field=models.ManyToManyField(blank=True, null=True, to='personagem.antescendente'),
        ),
        migrations.AddField(
            model_name='atributos',
            name='fk_Atributo',
            field=models.ManyToManyField(blank=True, null=True, to='personagem.atributo'),
        ),
        migrations.AddField(
            model_name='iventario',
            name='fk_armamento',
            field=models.ManyToManyField(blank=True, null=True, to='personagem.armamento'),
        ),
        migrations.AddField(
            model_name='iventario',
            name='fk_item',
            field=models.ManyToManyField(blank=True, null=True, to='personagem.item'),
        ),
        migrations.AddField(
            model_name='pericias',
            name='fk_Pericia',
            field=models.ManyToManyField(blank=True, null=True, to='personagem.pericia'),
        ),
        migrations.AddField(
            model_name='resistencias',
            name='fk_Resistencia',
            field=models.ManyToManyField(blank=True, null=True, to='personagem.resistencia'),
        ),
    ]
