# Generated by Django 4.1.7 on 2023-04-10 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("personagem", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcessoriosPersonagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.CharField(blank=True, max_length=100, null=True)),
                ("peso", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="AntescendentesPersonagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cadeia", models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name="ArmamentosPersonagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "categoria_0",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "categoria_1",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "categoria_2",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("alcance", models.IntegerField()),
                ("critico", models.CharField(blank=True, max_length=100, null=True)),
                ("dano", models.IntegerField()),
                ("espaco", models.IntegerField()),
                ("tipo", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="AtributosPersonagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cadeia", models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name="PericiasPersonagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cadeia", models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name="ResistenciasPersonagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cadeia", models.CharField(max_length=5000)),
            ],
        ),
        migrations.RemoveField(
            model_name="antescendentes",
            name="fk_Antescendente",
        ),
        migrations.RemoveField(
            model_name="atributos",
            name="fk_Atributo",
        ),
        migrations.RemoveField(
            model_name="pericias",
            name="fk_Pericia",
        ),
        migrations.RemoveField(
            model_name="resistencias",
            name="fk_Resistencia",
        ),
        migrations.RemoveField(
            model_name="iventario",
            name="fk_armamento",
        ),
        migrations.RemoveField(
            model_name="iventario",
            name="fk_item",
        ),
        migrations.RemoveField(
            model_name="personagem",
            name="fk_iventario",
        ),
        migrations.AddField(
            model_name="iventario",
            name="fk_personagem",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Antescendente",
        ),
        migrations.DeleteModel(
            name="Armamento",
        ),
        migrations.DeleteModel(
            name="Atributo",
        ),
        migrations.DeleteModel(
            name="Item",
        ),
        migrations.DeleteModel(
            name="Pericia",
        ),
        migrations.DeleteModel(
            name="Resistencia",
        ),
        migrations.AddField(
            model_name="armamentospersonagem",
            name="fk_personagem",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="personagem.personagem"
            ),
        ),
        migrations.AddField(
            model_name="acessoriospersonagem",
            name="fk_personagem",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="personagem.personagem"
            ),
        ),
        migrations.AddField(
            model_name="iventario",
            name="fk_acessorios",
            field=models.ManyToManyField(
                blank=True, null=True, to="personagem.acessoriospersonagem"
            ),
        ),
        migrations.AddField(
            model_name="iventario",
            name="fk_armamentos",
            field=models.ManyToManyField(
                blank=True, null=True, to="personagem.armamentospersonagem"
            ),
        ),
        migrations.AlterField(
            model_name="personagem",
            name="fk_antescendentes",
            field=models.OneToOneField(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="personagem.antescendentespersonagem",
            ),
        ),
        migrations.AlterField(
            model_name="personagem",
            name="fk_atributos",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="personagem.atributospersonagem",
            ),
        ),
        migrations.AlterField(
            model_name="personagem",
            name="fk_pericias",
            field=models.OneToOneField(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="personagem.periciaspersonagem",
            ),
        ),
        migrations.AlterField(
            model_name="personagem",
            name="fk_resistencias",
            field=models.OneToOneField(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="personagem.resistenciaspersonagem",
            ),
        ),
        migrations.DeleteModel(
            name="Antescendentes",
        ),
        migrations.DeleteModel(
            name="Atributos",
        ),
        migrations.DeleteModel(
            name="Pericias",
        ),
        migrations.DeleteModel(
            name="Resistencias",
        ),
    ]
