# Generated by Django 4.1.7 on 2023-04-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personagem", "0002_acessoriospersonagem_antescendentespersonagem_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="acessoriospersonagem",
            old_name="peso",
            new_name="espaco",
        ),
        migrations.AddField(
            model_name="acessoriospersonagem",
            name="nome",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="acessoriospersonagem",
            name="descricao",
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
