# Generated by Django 4.1.7 on 2023-04-11 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("session", "0019_acessorio_remove_acessorios_descricao_and_more"),
        (
            "personagem",
            "0004_personagem_enlouquecendo_personagem_inconsciente_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="personagem",
            name="fk_session",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="session.session",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="personagem",
            name="patente",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="personagem",
            name="trilha",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="personagem",
            name="NEX",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="personagem",
            name="idade",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
