# Generated by Django 4.1.7 on 2023-04-11 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("personagem", "0005_personagem_fk_session_personagem_patente_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="esforcobar",
            name="temporario",
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name="iventario",
            name="fk_acessorios",
        ),
        migrations.RemoveField(
            model_name="iventario",
            name="fk_armamentos",
        ),
        migrations.AddField(
            model_name="iventario",
            name="fk_acessorios",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="personagem.acessoriospersonagem",
            ),
        ),
        migrations.AddField(
            model_name="iventario",
            name="fk_armamentos",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="personagem.armamentospersonagem",
            ),
        ),
    ]
