# Generated by Django 4.1.7 on 2023-04-11 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("personagem", "0006_alter_esforcobar_temporario_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="armamentospersonagem",
            old_name="nome",
            new_name="descricao",
        ),
    ]
