# Generated by Django 4.1.7 on 2023-04-11 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("personagem", "0007_rename_nome_armamentospersonagem_descricao"),
    ]

    operations = [
        migrations.RenameField(
            model_name="armamentospersonagem",
            old_name="descricao",
            new_name="arma",
        ),
    ]
