# Generated by Django 4.1.7 on 2023-04-11 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personagem", "0008_rename_descricao_armamentospersonagem_arma"),
    ]

    operations = [
        migrations.AlterField(
            model_name="armamentospersonagem",
            name="alcance",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="armamentospersonagem",
            name="dano",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
