# Generated by Django 4.1.7 on 2023-04-12 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("personagem", "0009_alter_armamentospersonagem_alcance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="personagem",
            name="fk_user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
