# Generated by Django 4.1.7 on 2023-04-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personagem", "0011_perfil"),
    ]

    operations = [
        migrations.CreateModel(
            name="PerfilImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="imagem/")),
            ],
        ),
    ]
