# Generated by Django 4.1.7 on 2023-04-13 21:20

from django.db import migrations, models
import django.db.models.deletion
import django_base64field.fields


class Migration(migrations.Migration):

    dependencies = [
        ("personagem", "0012_perfilimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="personagem",
            name="fk_perfil_img",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="personagem.perfilimage",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="perfil",
            name="image",
            field=django_base64field.fields.Base64Field(
                blank=True, default="", max_length=900000, null=True
            ),
        ),
        migrations.AlterField(
            model_name="perfilimage",
            name="image",
            field=django_base64field.fields.Base64Field(
                blank=True, default="", max_length=900000, null=True
            ),
        ),
    ]
