# Generated by Django 4.1.7 on 2023-04-14 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personagem", "0013_personagem_fk_perfil_img_alter_perfil_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="personagem",
            name="sexo",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
